[host_system]

# Define computer centre.
compcentre="ECMWF"

# Define hosts
hosts = ["hpc-login"]

# Location of working data, fast and large system
# Experiment identifier and directories
# EXP is defined when an experiment is started by "Harmonie start ..."
sfx_exp_data = "/scratch/@USER@/sfx_data/@EXP@"
# directory for scripts, compiled objects, executables
sfx_exp_lib = "/scratch/@USER@/sfx_data/@EXP@/lib@STREAM@"
joboutdir = "/perm/@USER@/sfx_data/"
login_host = "hpc-login"
hm_cs = "gfortran"
parch = ""
mkdir = "mkdir -p"
rsync = "rsync  -rltoDvhL"
scheduler_pythonpath = "/perm/sbu/offline_modules/apps/pysurfex-scheduler/:/usr/local/apps/ecflow/5.8.1/lib/python3.8/site-packages/"
surfex_config = "aa.GNU.offline"
troika = "troika"
