# SURFEX offline experiment configuration file
#

[GENERAL]
######################################################################################################
# General (not grouped settings)
######################################################################################################

HH_LIST="00-21:3"                       # Which cycles to run, replaces FCINT
LL_LIST="48,3,3,3,3,3,3,3"              # Forecast lengths for the cycles [h], replaces LL, LLMAIN
                                        # The LL_LIST list is wrapped around if necessary, to fit HH_LIST

[COMPILE]
####################################################################################################
# Compilation settings
#####################################################################################################
BUILD = false                         # Turn on or off the compilation and binary build (true/false)

[GEOMETRY]
#####################################################################################################
# Geometry
#####################################################################################################
DOMAIN = "DRAMMEN"                  # See definitions in config/Harmonie_domains.json

[INITIAL_CONDITIONS]
ANASURF = "gridpp"
# "/nobackup/prod2/cooper/BD_archive/2020/09/16/00/fc20200916_00+003
PREP_INPUT_FILE = "@PYSURFEX_EXPERIMENT@/nam/prep_from_namelist_values.json"
PREP_INPUT_FILETYPE = "json"
PREP_PGDFILE = ""
PREP_PGDFILETYPE = ""


[INITIAL_CONDITIONS.FG4OI]
INPUTFILE = "https://thredds.met.no/thredds/dodsC/meps25epsarchive/@YYYY@/@MM@/@DD@/meps_det_2_5km_@YYYY@@MM@@DD@T@HH@Z.nc"
# INPUTFILE = "/tmp/host1/testdata/fc@YYYY@@MM@@DD@@HH@+@LLLL@grib2"
# INPUTFILE = "@SFX_EXP_DATA@/archive/@YYYY@/@MM@/@DD@/03/SURFOUT.@YYYY@@MM@@DD@_06h00.nc"
FILEFORMAT = "netcdf"
# FILEFORMAT = "grib2"
# FILEFORMAT = "surfex"
CONVERTER = "none"
INPUT_GEO_FILE = ""     # Needed for some surfex file types

[INITIAL_CONDITIONS.FG4OI.air_temperature_2m]

[INITIAL_CONDITIONS.FG4OI.relative_humidity_2m]

[INITIAL_CONDITIONS.FG4OI.surface_snow_thickness]
CONVERTER = "sweclim"

[INITIAL_CONDITIONS.FG4OI.altitude]
CONVERTER = "phi2m"

[FORECAST]
#####################################################################################################
#  Forecast model (physics + dynamics and output)
#####################################################################################################

PHYSICS = "arome"
ENSMSEL = []                            # Ensemble members to run (list with member numbers)

FORC_ZS = true

[FORCING]
PATTERN = "https://thredds.met.no/thredds/dodsC/meps25epsarchive/@YYYY@/@MM@/@DD@/meps_det_2_5km_@YYYY@@MM@@DD@T@HH@Z.nc"
INPUT_FORMAT = "netcdf"
INPUT_GEO_FILE = ""      # Needed for some surfex file types
# PATTERN = "/tmp/host1/testdata/fc@YYYY@@MM@@DD@@HH@+@LLLL@grib2"
# INPUT_FORMAT = "grib2"
RAIN_CONVERTER = "totalprec"
ZREF = "ml"
ZVAL = "constant"
UREF = "ml"
UVAL = "constant"
ZSORO_CONVERTER = "phi2m"
SCA_SW = "constant"
CO2 = "constant"
WIND_CONVERTER = "windspeed"
WINDDIR_CONVERTER = "winddir"
DEBUG = false

[SYSTEM]
