# 
# SURFEX experiment configuration file
#

[general]
loglevel = "INFO"
cnmexp = ""
tstep = 60
realization =  -1
realizations = []
os_macros = ["HOME"]
            
hh_list="00-21:3"                       # Which cycles to run, replaces FCINT
ll_list="48,3,3,3,3,3,3,3"              # Forecast lengths for the cycles [h], replaces LL, LLMAIN
                                        # The LL_LIST list is wrapped around if necessary, to fit HH_LIST

[general.times]
cycle_length = "PT3H"



[compile]
####################################################################################################
# Compilation settings
#####################################################################################################
cmake = true                         # Build with CMake
build = true                         # Turn on or off the compilation and binary build (true/false)


#####################################################################################################
# Geometry
#####################################################################################################

[domain]
   name = "DRAMMEN"
   nimax = 50
   njmax = 60
   xloncen = 10.0
   xlatcen = 60.0
   xdx = 2500.0
   xdy = 2500.0
   ilone = 0
   ilate = 0
   xlon0 = 10.0
   xlat0 = 60.0


[initial_conditions]
anasurf = "gridpp"
# "/nobackup/prod2/cooper/BD_archive/2020/09/16/00/fc20200916_00+003
prep_input_file = "@pysurfex_experiment@/nam/prep_from_namelist_values.json"
prep_input_filetype = "json"
prep_pgdfile = ""
prep_pgdfiletype = ""


[initial_conditions.fg4oi]
inputfile = "https://thredds.met.no/thredds/dodsC/meps25epsarchive/@YYYY@/@MM@/@DD@/meps_det_2_5km_@YYYY@@MM@@DD@T@HH@Z.nc"
# inputfile = "@sfx_exp_data@/archive/@YYYY@/@MM@/@DD@/@HH@/SURFOUT.@YYYY@@MM@@DD@_@HH_LL@h00.nc"
# inputfile = "/tmp/host1/testdata/fc@YYYY@@MM@@DD@@HH@+@LLLL@grib2"
fileformat = "netcdf"
# fileformat = "grib2"
# fileformat = "surfex"
converter = "none"
input_geo_file = ""     # Needed for some surfex file types

[initial_conditions.fg4oi.air_temperature_2m]

[initial_conditions.fg4oi.relative_humidity_2m]

[initial_conditions.fg4oi.surface_snow_thickness]
converter = "sweclim"

[initial_conditions.fg4oi.altitude]
converter = "phi2m"



[forecast]
#####################################################################################################
#  Forecast model (physics + dynamics and output)
#####################################################################################################

physics = "arome"
ensmsel = []                            # Ensemble members to run (list with member numbers)
forc_zs = true

[forcing]
# After 2023013123
# pattern = "https://thredds.met.no/thredds/dodsC/metpparchive/@YYYY@/@MM@/@DD@/met_analysis_1_0km_nordic_@YYYY@@MM@@DD@T@HH@Z.nc"
# Before 2023020100
pattern = "https://thredds.met.no/thredds/dodsC/metpparchivev3/@YYYY@/@MM@/@DD@/met_analysis_1_0km_nordic_@YYYY@@MM@@DD@T@HH@Z.nc"
# Local file system paths at MET-Norway
# pattern = "/lustre/storeB/project/metproduction/products/yr_short/met_analysis_1_0km_nordic_@YYYY@@MM@@DD@T@HH@Z.nc"
# pattern = "/lustre/storeB/immutable/archive/projects/metproduction/yr_short//@YYYY@/@MM@/@DD@/met_analysis_1_0km_nordic_@YYYY@@MM@@DD@T@HH@Z.nc
# pattern = "/lustre/storeB/project/metkl/klinogrid/archive/met_nordic_analysis/v3/@YYYY@/@MM@/@DD@/met_analysis_1_0km_nordic_@YYYY@@MM@@DD@T@HH@Z.nc"
input_format = "netcdf"
input_geo_file = ""      # Needed for some surfex file types
# pattern = "/tmp/host1/testdata/fc@YYYY@@MM@@DD@@HH@+@LLLL@grib2"
# input_format = "grib2"
zref = "screen"
zval = "constant"
uref = "screen"
uval = "constant"
qa_converter = "rh2q_mslp"
zsoro_converter = "none"
rain_converter = "calcrain"
snow_converter = "calcsnow"
dir_sw_converter = "analysis"
sca_sw = "constant"
lw_converter = "analysis"
co2 = "constant"
wind_converter = "none"
winddir_converter = "none"
ps_converter = "mslp2ps"
debug = false
timestep = 3600
analysis = true
modify_forcing = false
interpolation = "bilinear"

