sites:
  localhost:
    type: direct
    connection: local

  aa:
    type: slurm
    connection: ssh
    host: aa-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  ab:
    type: slurm
    connection: ssh
    host: ab-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  ac:
    type: slurm
    connection: ssh
    host: ac-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  ad:
    type: slurm
    connection: ssh
    host: ad-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  hpc:
    type: slurm
    connection: ssh
    host: hpc-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  nebula:
    type: slurm
    connection: local
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    sbatch_command: "sbatch"
    scancel_command: 'scancel -f'

  ppi-rhel8:
    type: sge
    connection: local
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "sge_add_output", "sge_bubble"]
    qsub_command: "qsub_v"
    qdel_command: 'qdel'

  hpc2020:
    type: slurm
    connection: ssh
    host: hpc2020-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  ecs:
    type: slurm
    connection: ssh
    host: ecs-batch
    kill_sequence: [[5, 2], [10, 9]]
    pre_submit: ["create_output_dir"]
    preprocess: ["remove_top_blank_lines", "slurm_add_output", "slurm_bubble"]
    at_exit: ["copy_submit_logfile"]
    sbatch_command: "ecsbatch"
    scancel_command: 'scancel -f'

  new_site:
    type: deode
    connection: local

